# Generated by Django 4.0.4 on 2022-04-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_password', models.CharField(max_length=100)),
                ('account_data', models.CharField(max_length=200)),
            ],
        ),
    ]
